# Generated by Django 6.1.1 on 2026-09-26 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_type", models.CharField(max_length=30)),
                ("category_name", models.CharField(max_length=150)),
                ("category_description", models.TextField(blank=True, null=True)),
                ("category_up_date", models.DateTimeField(blank=True, null=True)),
                ("category_add_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CuratedCollection",
            fields=[
                (
                    "collection_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("collection_name", models.CharField(max_length=255)),
                ("collection_description", models.TextField(blank=True, null=True)),
                ("collection_add_date", models.DateTimeField(auto_now_add=True)),
                ("collection_up_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Filter",
            fields=[
                ("filter_id", models.AutoField(primary_key=True, serialize=False)),
                ("filter_type", models.CharField(max_length=50)),
                ("filter_name", models.CharField(max_length=150)),
                ("filter_add_date", models.DateTimeField(auto_now_add=True)),
                ("filter_up_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PriceModel",
            fields=[
                (
                    "price_model_id",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
                ("price_model_name", models.CharField(max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("source_id", models.AutoField(primary_key=True, serialize=False)),
                ("source_name", models.CharField(max_length=150)),
                ("source_domain", models.CharField(max_length=253, unique=True)),
                ("source_trust", models.CharField(max_length=30)),
                ("source_add_date", models.DateTimeField(auto_now_add=True)),
                ("source_up_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_fname", models.CharField(max_length=100)),
                ("user_lname", models.CharField(max_length=100)),
                ("user_email", models.EmailField(max_length=254, unique=True)),
                ("user_role", models.CharField(max_length=30)),
                ("user_status", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="CollectionResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField()),
                ("add_date", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landing.curatedcollection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("resource_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("resource_title", models.CharField(max_length=150)),
                ("resource_url", models.URLField(max_length=2048)),
                (
                    "resource_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("resource_snippet", models.TextField(blank=True, null=True)),
                ("resource_up_date", models.DateTimeField(blank=True, null=True)),
                ("resource_pub_date", models.DateTimeField(blank=True, null=True)),
                ("resource_add_date", models.DateTimeField(auto_now_add=True)),
                (
                    "resource_format",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "resource_duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("price_reviewed", models.BooleanField(default=False)),
                ("price_reviewed_date", models.DateTimeField(blank=True, null=True)),
                ("other_metadata", models.JSONField(blank=True, null=True)),
                (
                    "collections",
                    models.ManyToManyField(
                        related_name="resources",
                        through="landing.CollectionResource",
                        to="landing.curatedcollection",
                    ),
                ),
                (
                    "price_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="landing.pricemodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="collectionresource",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="landing.resource"
            ),
        ),
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landing.category",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landing.resource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="resource",
            name="categories",
            field=models.ManyToManyField(
                related_name="resources",
                through="landing.ResourceCategory",
                to="landing.category",
            ),
        ),
        migrations.CreateModel(
            name="ResourceFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="landing.filter"
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landing.resource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="resource",
            name="filters",
            field=models.ManyToManyField(
                related_name="resources",
                through="landing.ResourceFilter",
                to="landing.filter",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resources",
                to="landing.source",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="curator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sources",
                to="landing.user",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="curator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resources",
                to="landing.user",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="price_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="price_reviews",
                to="landing.user",
            ),
        ),
        migrations.AddField(
            model_name="filter",
            name="curator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="filters",
                to="landing.user",
            ),
        ),
        migrations.AddField(
            model_name="curatedcollection",
            name="curator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collections",
                to="landing.user",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="curator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="landing.user",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionresource",
            constraint=models.UniqueConstraint(
                fields=("collection", "resource"), name="unique_collection_resource"
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionresource",
            constraint=models.UniqueConstraint(
                fields=("collection", "sort_order"), name="unique_collection_sort_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="resourcecategory",
            constraint=models.UniqueConstraint(
                fields=("resource", "category"), name="unique_resource_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="resourcefilter",
            constraint=models.UniqueConstraint(
                fields=("resource", "filter"), name="unique_resource_filter"
            ),
        ),
        migrations.AddConstraint(
            model_name="filter",
            constraint=models.UniqueConstraint(
                fields=("filter_type", "filter_name"), name="unique_filter_type_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("category_type", "category_name"),
                name="unique_category_type_name",
            ),
        ),
    ]
